#ifndef _GLOBAL_INDEX_H
#define _GLOBAL_INDEX_H

#define MAIN_LBL_OTDR                           1               //OTDR
#define MAIN_LBL_VFL                            2               //红光源
#define MAIN_LBL_LIGHT_SOURCE                   3               //稳定光源
#define MAIN_LBL_OPM                            4               //光功率计
#define MAIN_LBL_FIP                            5               //光纤端面
#define MAIN_LBL_RJ45                           6               //网线
#define MAIN_LBL_FILE                           7               //文件管理
#define MAIN_LBL_SYSTEM_SET                     8               //系统设置
#define VFL_LBL_CLOSE                           9               //关闭
#define VFL_LBL_CW                              10              //连续
#define VFL_LBL_2HZ                             11              //闪烁
#define VFL_LBL_WARNING                         12              //请勿直视端口！
#define LIGHT_SOURCE_LBL_CLOSE                  13              //关闭
#define LIGHT_SOURCE_LBL_WAVE                   14              //λ
#define LIGHT_SOURCE_LBL_HZ                     15              //HZ
#define LIGHT_SOURCE_LBL_FREQUENCE              16              //频率：
#define LIGHT_SOURCE_LBL_START                  17              //开始
#define OPM_LBL_WAVELENGTH                      18              //λ
#define OPM_LBL_DBM                             19              //dBm
#define OPM_LBL_REF                             20              //REF
#define OPM_LBL_ZERO_ADJUST                     21              //调零
#define FIP_LBL_OPEN                            22              //打开
#define FIP_LBL_SAVE                            23              //保存
#define FIP_LBL_ALIGN                           24              //居中
#define FILE_LBL_PATH                           25              //路径
#define FILE_LBL_FILE_TYPE                      26              //文件类型
#define FILE_LBL_OPEN                           27              //打开
#define FILE_LBL_SELECT_ALL                     28              //全选
#define FILE_LBL_MKDIR                          29              //新建文件夹
#define FILE_LBL_RENAME                         30              //重命名
#define FILE_LBL_COPY                           31              //复制
#define FILE_LBL_PASTE                          32              //粘贴
#define FILE_LBL_DELETE                         33              //删除
#define FILE_LBL_FILE_NAME                      34              //文件名
#define FILE_LBL_DATE                           35              //日期
#define FILE_LBL_NO_DISK                        36              //未检测到sd卡和U盘！
#define FILE_LBL_SAME_FILE                      37              //该目录存在同名文件！
#define FILE_LBL_CREATE_FOLDER_FAILED           38              //创建文件夹失败！
#define FILE_LBL_INVALID_FOLDER_NAME            39              //请输入有效的文件夹名称
#define FILE_LBL_LONG_FILE_NAME                 40              //文件名过长，请重新输入
#define FILE_LBL_RENAME_FAILED                  41              //重命名文件失败！
#define FILE_LBL_FILE_NOT_EXIST                 42              //文件或文件夹不存在！
#define FILE_LBL_NOT_PASTE                      43              //不能粘贴到当前目录
#define FILE_LBL_FILE_ALREADY_EXIST             44              //文件已存在，是否覆盖？
#define FILE_LBL_DELETE_FILE                    45              //确定要删除文件或文件夹？
#define SYSTEM_LBL_PARAMETER_SET                46              //进行系统参数的设定
#define SYSTEM_LBL_KEY_WARNING                  47              //按键音
#define SYSTEM_LBL_DATE                         48              //日期
#define SYSTEM_LBL_TIME                         49              //时间
#define SYSTEM_LBL_LANGUGAGE                    50              //语言
#define SYSTEM_LBL_AUTO_OFF                     51              //自动关机
#define SYSTEM_LBL_STAND_BY_TIME                52              //待机时间
#define SYSTEM_LBL_RESTORE_FACTORY_DEFAULT      53              //恢复出厂设置
#define SYSTEM_LBL_UPDATE                       54              //升级
#define SYSTEM_LBL_SYSTEM_INFO                  55              //系统信息
#define SYSTEM_LBL_CONFIRM                      56              //确定
#define SYSTEM_LBL_CANCEL                       57              //取消
#define SYSTEM_LBL_CONFIRM_TO_RESTORE           58              //确定要恢复出厂设置吗？
#define SYSTEM_LBL_RESTORING                    59              //正在恢复到默认设置…
#define SYSTEM_LBL_RESTORED_SUCCESS             60              //恢复出厂设置成功，请重启系统
#define SYSTEM_LBL_INPUT_BATTERY                61              //必须插入电池且电量大于50%！
#define SYSTEM_LBL_PRESS_UPDATE                 62              //按下升级按钮启动
#define SYSTEM_LBL_POWER_OVER_50                63              //升级前，请确保电量大于50%
#define SYSTEM_LBL_LOAD_DISK                    64              //尝试加载sd卡或U盘…
#define SYSTEM_LBL_SEARCH_UPDATE_FILE           65              //正在搜索升级文件…
#define SYSTEM_LBL_INSERT_DISK                  66              //请插入sd卡或U盘！
#define SYSTEM_LBL_INPUT_UPDATE_FILE            67              //请将升级文件放入sd卡或U盘中！
#define SYSTEM_LBL_INSUFFICIENT_DISK_SPACE      68              //磁盘空间不足，请使用修复软件修复
#define SYSTEM_LBL_UNZIPPING_UPDATE_FILE        69              //正在解压升级文件…
#define SYSTEM_LBL_UNZIP_FAILED                 70              //解压失败，请重启系统再次升级
#define SYSTEM_LBL_DAMAGED_UPDATING_FILE        71              //升级包损坏
#define SYSTEM_LBL_WRITING_SECTOR               72              //正在写入扇区…
#define SYSTEM_LBL_UPDATE_SUCCESS               73              //升级成功…
#define SYSTEM_LBL_MODULE                       74              //模块：
#define SYSTEM_LBL_SERIAL_NUM                   75              //序列号：
#define SYSTEM_LBL_VERSION                      76              //版本：
#define SYSTEM_LBL_SOFTWARE_DATE                77              //软件日期：
#define OTDR_SET_LBL_TEST                       78              //测试
#define OTDR_SET_LBL_ANALYSIS                   79              //分析
#define OTDR_SET_LBL_THRESHOLD                  80              //阈值
#define OTDR_SET_LBL_REPORT                     81              //报表
#define OTDR_SET_LBL_MEASURE                    82              //进行OTDR测试设定
#define OTDR_SET_LBL_TEST_MODE                  83              //测量模式
#define OTDR_SET_LBL_RT                         84              //实时
#define OTDR_SET_LBL_AVERAGE                    85              //平均
#define OTDR_SET_LBL_RANGE                      86              //量程
#define OTDR_SET_LBL_PULSE                      87              //脉宽
#define OTDR_SET_LBL_TEST_TIME                  88              //测试时长
#define OTDR_SET_LBL_REAL_TIME                  89              //实时
#define OTDR_SET_LBL_DISTANCE_UNIT              90              //距离单位
#define OTDR_SET_LBL_WAVE_LENGTH                91              //波长
#define OTDR_SET_LBL_ANALYSIS_PARA              92              //分析参数
#define OTDR_SET_LBL_REFRACTIVE_INDEX           93              //折射率
#define OTDR_SET_LBL_BACK_SCATTERING            94              //背向散射
#define OTDR_SET_LBL_HELIX_FACTOR               95              //余长系数
#define OTDR_SET_LBL_DEFAULT                    96              //默认值
#define OTDR_SET_LBL_LANUCH_RECEIVE_FIBER       97              //注入光纤和接收光纤
#define OTDR_SET_LBL_FIBER_LENGTH               98              //按光纤长度
#define OTDR_SET_LBL_FIBER_EVENT                99              //按事件
#define OTDR_SET_LBL_LANUCH_FIBER_LENGTH        100             //注入光纤长度
#define OTDR_SET_LBL_LANUCH_FIBER_EVENT         101             //注入光纤事件
#define OTDR_SET_LBL_RECEIVE_FIBER_LENGTH       102             //接收光纤长度
#define OTDR_SET_LBL_RECEIVE_FIBER_EVENT        103             //接收光纤事件
#define OTDR_SET_LBL_FIBER_EVENT_OUT_OF_RANGE   104             //注入/接收光纤事件超出范围（1~10）
#define OTDR_SET_LBL_FIBER_LENGTH_M_RANGE       105             //请输入0.0到360000.0之间的数值
#define OTDR_SET_LBL_FIBER_LENGTH_KM_RANGE      106             //请输入0.0到360.0000之间的数值
#define OTDR_SET_LBL_FIBER_LENGTH_FT_RANGE      107             //请输入0.0到1181102.4之间的数值
#define OTDR_SET_LBL_FIBER_LENGTH_KFT_RANGE     108             //请输入0.0到1181.1024之间的数值
#define OTDR_SET_LBL_FIBER_LENGTH_YD_RANGE      109             //请输入0.0到393700.8之间的数值
#define OTDR_SET_LBL_FIBER_LENGTH_MI_RANGE      110             //请输入0.0到223.6936之间的数值
#define OTDR_SET_LBL_CURVE_THRESHOLD            111             //曲线通过阈值设定
#define OTDR_SET_LBL_CONNECTION_LOSS            112             //接头损耗
#define OTDR_SET_LBL_CONNECTOR_LOSS             113             //连接器损耗
#define OTDR_SET_LBL_REFLECTIVITY               114             //反射率
#define OTDR_SET_LBL_ATTENUATION                115             //衰减
#define OTDR_SET_LBL_SECTION_LOSS               116             //跨段损耗
#define OTDR_SET_LBL_SECTION_DISTANCE           117             //跨段长度
#define OTDR_SET_LBL_SECTION_ORL                118             //跨段ORL
#define OTDR_SET_LBL_ANALYSIS_SETTING           119             //进行分析阈值设定
#define OTDR_SET_LBL_SPLICING_LOSS              120             //熔接损耗
#define OTDR_SET_LBL_END_LOSS                   121             //光纤末端损耗
#define OTDR_SET_LBL_REPORT_SETTING             122             //进行报表信息设定
#define OTDR_SET_LBL_NAME_CABLE                 123             //光缆编号
#define OTDR_SET_LBL_NAME_FIBER                 124             //光纤编号
#define OTDR_SET_LBL_LOCATION_A                 125             //位置a
#define OTDR_SET_LBL_LOCATION_B                 126             //位置b
#define OTDR_SET_LBL_NAME_TEST                  127             //任务编号
#define OTDR_SET_LBL_USER                       128             //用户
#define OTDR_SET_LBL_NOTE                       129             //注释
#define OTDR_SET_LBL_DEFAULT_PATH               130             //文件默认保存路径：
#define OTDR_SET_LBL_ERROR_ENTER                131             //数值越界了，请输入
#define OTDR_SET_LBL_ENSURE_CHANGE              132             //是否应用阈值设置到事件测试中？
#define OTDR_SET_REEVENT_ANALYZE                133             //重新事件分析中，请稍后…
#define OTDR_DEFAULT_FOLDER_LBL_TITLE           134             //默认文件夹
#define OTDR_DEFAULT_FOLDER_LBL_CONFIRM         135             //确认
#define OTDR_LBL_CARRAY_OUT                     136             //确认执行
#define OTDR_LBL_SIGNAL_CONTINUE                137             //光纤中有光，确认继续？
#define OTDR_LBL_CHECAK_TRANSMISSION            138             //光纤有光检查中…
#define OTDR_LBL_CHECKING_CONNECTOR             139             //光纤接头检查中…
#define OTDR_LBL_BAD_CONNECTOR_CONTINUE         140             //光纤接头未接好，确认继续？
#define OTDR_LBL_EVENAT_ANALYZING               141             //事件分析中…
#define OTDR_LBL_PASS                           142             //通过
#define OTDR_LBL_FAIL                           143             //不通过
#define OTDR_LBL_STYLE                          144             //类型
#define OTDR_LBL_NUMBER                         145             //序号
#define OTDR_LBL_DISTANCE                       146             //距离
#define OTDR_LBL_DISTANCE_M                     147             //距离(m)
#define OTDR_LBL_DISTANCE_KM                    148             //距离(km)
#define OTDR_LBL_DISTANCE_FT                    149             //距离(ft)
#define OTDR_LBL_DISTANCE_KFT                   150             //距离(kft)
#define OTDR_LBL_DISTANCE_YD                    151             //距离(yd)
#define OTDR_LBL_DISTANCE_MILE                  152             //距离(mile)
#define OTDR_LBL_LOSS                           153             //损耗
#define OTDR_LBL_LOSS_DB                        154             //损耗(dB)
#define OTDR_LBL_REF                            155             //反射率
#define OTDR_LBL_REF_DB                         156             //反射率(dB)
#define OTDR_LBL_ATT                            157             //衰减率
#define OTDR_LBL_ATT_DB                         158             //衰减率(dB/km)
#define OTDR_LBL_SAVE_FILE                      159             //保存文件
#define OTDR_LBL_OPEN_FILE                      160             //打开文件
#define OTDR_LBL_SAVE_SUCCESSFULLY              161             //保存成功:
#define OTDR_LBL_SAVE_FAILED                    162             //保存失败:
#define OTDR_LBL_EXIT                           163             //退出
#define OTDR_LBL_FIBER_LENGTH                   164             //光纤长度：
#define OTDR_LBL_WAVE                           165             //波长（nm）
#define OTDR_LBL_TOTAL_ATT                      166             //总衰减(dB)
#define OTDR_LBL_TOTAL_ATT_1                    167             //总衰减：
#define OTDR_LBL_ATT_FACTOR                     168             //衰减系数(dB/km)
#define OTDR_LBL_ATT_FACTOR_1                   169             //衰减系数：
#define OTDR_LBL_TOTAL_EVENT_NUM                170             //事件总数
#define OTDR_LBL_UNABLE_TO_SET_SPANS            171             //无法设置跨段！
#define OTDR_LBL_SWITCH_LINK_MAP                172             //请按下[SHIFT]+[ENTER]键切换到链路地图.
#define OTDR_LBL_SWITCH_EVENT_TABLE             173             //请按下[SHIFT]+[ENTER]键切换到事件列表.
#define OTDR_REPORT_LBL_TITLE                   174             //OTDR报告
#define OTDR_REPORT_LBL_SUMMARY                 175             //摘要表
#define OTDR_REPORT_LBL_FILE_NAME               176             //文件名：
#define OTDR_REPORT_LBL_COMPANY_NAME            177             //公司：
#define OTDR_REPORT_LBL_TEST_DATE               178             //测试日期:
#define OTDR_REPORT_LBL_CUSTOMER                179             //客户：
#define OTDR_REPORT_LBL_TEST_TIME               180             //测试时间
#define OTDR_REPORT_LBL_TASK_ID                 181             //任务ID：
#define OTDR_REPORT_LBL_CABLE_NUMBER            182             //光缆标识：
#define OTDR_REPORT_LBL_FIBER_NUMBER            183             //光纤标识：
#define OTDR_REPORT_LBL_DIRECTION               184             //方向：
#define OTDR_REPORT_LBL_OPERATOR_A              185             //操作员A：
#define OTDR_REPORT_LBL_OPERATOR_B              186             //操作员B：
#define OTDR_REPORT_LBL_LOACATION_A             187             //位置A：
#define OTDR_REPORT_LBL_LOACATION_B             188             //位置B：
#define OTDR_REPORT_LBL_NOTE                    189             //注释：
#define OTDR_REPORT_LBL_MEASURING_MODEL         190             //测量平台：
#define OTDR_REPORT_LBL_SERIAL_NUMBER           191             //序列号：
#define OTDR_REPORT_LBL_VERSION                 192             //版本：
#define OTDR_REPORT_LBL_TRACE                   193             //OTDR曲线
#define OTDR_REPORT_LBL_MARKER_INFO             194             //标记线信息
#define OTDR_REPORT_LBL_MARKER_A                195             //标记线A
#define OTDR_REPORT_LBL_MARKER_b                196             //标记线B
#define OTDR_REPORT_LBL_DISTANCE                197             //A到B距离
#define OTDR_REPORT_LBL_MARKER_LOSS             198             //A到B光回损
#define OTDR_REPORT_LBL_MARKER_ATTN             199             //A到B的差值
#define OTDR_REPORT_LBL_ORL                     200             //跨段ORL
#define OTDR_REPORT_LBL_EVENTS                  201             //事件表
#define OTDR_REPORT_LBL_ORIGINALEVENT           202             //起点事件
#define OTDR_REPORT_LBL_END_EVENT               203             //终点事件
#define OTDR_REPORT_LBL_SPLICE_EVENT            204             //熔接事件
#define OTDR_REPORT_LBL_GAIN_EVENT              205             //增益事件
#define OTDR_REPORT_LBL_RL_EVENT                206             //回波事件
#define OTDR_REPORT_LBL_REFLECTION_EVENT        207             //反射事件
#define OTDR_REPORT_LBL_UNDERPOWER_EVENT        208             //光功率不足事件
#define OTDR_REPORT_LBL_ANALYSIS_END_EVENT      209             //分析结束事件
#define OTDR_REPORT_LBL_CUMULATIVE_LOSS         210             //累计损耗(dB)
#define OTDR_REPORT_LBL_PARAMETER_SETTING       211             //曲线参数、阈值和设置信息
#define OTDR_REPORT_LBL_PARAMETER               212             //参数
#define OTDR_REPORT_LBL_WAVELENGTH              213             //波长：
#define OTDR_REPORT_LBL_PULSE                   214             //脉宽：
#define OTDR_REPORT_LBL_RANGE                   215             //量程：
#define OTDR_REPORT_LBL_AVG_TIME                216             //平均时间：
#define OTDR_REPORT_LBL_THRESHOLD               217             //通过/不通过阈值
#define OTDR_REPORT_LBL_CONNECTION_LOSS         218             //接头损耗：
#define OTDR_REPORT_LBL_CONNECTOR_LOSS          219             //连接器损耗：
#define OTDR_REPORT_LBL_REF                     220             //反射率：
#define OTDR_REPORT_LBL_ATT                     221             //衰减：
#define OTDR_REPORT_LBL_LOSS                    222             //跨段损耗：
#define OTDR_REPORT_LBL_LENGTH                  223             //跨段长度：
#define OTDR_REPORT_LBL_SPAN_ORL                224             //跨段ORL：
#define OTDR_REPORT_LBL_SETUP                   225             //设置
#define OTDR_REPORT_LBL_REFRACTIVE_INDEX        226             //折射率：
#define OTDR_REPORT_LBL_SPLICING_THRE           227             //熔接损耗阈值：
#define OTDR_REPORT_LBL_BACK_SCATTERING         228             //背向散射：
#define OTDR_REPORT_LBL_HELIX_FACTOR            229             //余长系数：
#define OTDR_REPORT_LBL_FIBER_THRE              230             //光纤末端阈值：
#define OTDR_REPORT_LBL_TEST_LOCATION           231             //采样点：
#define OTDR_REPORT_LBL_TEST_RESULT             232             //测试结果：
#define OTDR_REPORT_LBL_AVG_SPLICE_LOSS         233             //平均熔接损耗：
#define OTDR_REPORT_LBL_MAX_SPLICE_LOSS         234             //最大熔接损耗：
#define OTDR_REPORT_LBL_AVG_ATT                 235             //平均衰减：
#define OTDR_REPORT_LBL_NAME                    236             //姓名：
#define OTDR_REPORT_LBL_DATE                    237             //日期：
#define IME_LBL_REFRACTIVE_LIMIT                238             //请输入1.000000~2.000000之间的数字
#define IME_LBL_BACKLOSS_LIMIT_1310             239             //请输入-89.44  ~  -65.45之间的数字
#define IME_LBL_BACKLOSS_LIMIT_1550             240             //请输入-91.86~-71.87之间的数字
#define IME_LBL_EXEC_LIMIT                      241             //请输入0.00  ~  10.00之间的数字
#define IME_LBL_SPLICLOSS_LIMIT                 242             //请输入0.010 ~ 5.000之间的数字
#define IME_LBL_ENDLOSS_LIMIT                   243             //请输入1.000 ~ 25.000之间的数字
#define DIALOG_LBL_FILEOPEN_ERR                 244             //打开文件失败！
#define DIALOG_LBL_FILENAME_INVAILD             245             //输入的文件名无效！
#define DIALOG_LBL_INSERT_DETECTOR              246             //请连接端面检测仪
#define DIALOG_LBL_NOTE                         247             //提示
#define DIALOG_LBL_CREAT_REPORT                 248             //确认创建报告？
#define DIALOG_LBL_PURCHASE_FIP                 249             //请购买端面检查仪功能！
#define DIALOG_LBL_PURCHASE_LS                  250             //请购买光源功能！
#define DIALOG_LBL_PURCHASE_RJ45                251             //请购买RJ45功能！
#define DIALOG_LBL_LEASE_DATE                   252             //租赁日期已到，请继续购买！
#define DIALOG_LBL_PURCHASE                     253             //此功能尚未开通！
#define DIALOG_SAVE_SUCCESS                     254             //保存文件成功
#define DIALOG_SOR_FILEOPEN_ERR                 255             //文件打开失败
#define DIALOG_SOR_SYSTEM_ERR                   256             //文件系统出错
#define SYSTEM_LANGUAGE_LBL_CHINA               257             //中文
#define SYSTEM_LANGUAGE_LBL_ENGLISH             258             //English
#define SYSTEM_LANGUAGE_LBL_SPANISH             259             //Español
#define SYSTEM_LANGUAGE_LBL_FRANCE              260             //France
#define SYSTEM_LANGUAGE_LBL_PORTUGAL            261             //Portuguese
#define SYSTEM_LANGUAGE_LBL_RUSSIAN             262             //Русский
#define SYSTEM_LANGUAGE_LBL_ITALY               263             //意大利语
#define SYSTEM_LANGUAGE_LBL_THAI                264             //泰语
#define SYSTEM_LBL_USER_GUIDE                   265             //用户指南
#define OTDR_CURVE_LBL_SAVE_SUCCESS             266             //保存成功：
#define OTDR_CURVE_LBL_SAVE_FAILED              267             //保存失败！
#define RJ45_LBL_SEQUENCE                       268             //网线测序
#define RJ45_LBL_RANGE                          269             //网线测距
#define RJ45_LBL_SEARCH                         270             //网线寻线
#define RJ45_LBL_STANDARD                       271             //标准
#define RJ45_LBL_CHECK                          272             //检测
#define RJ45_LBL_RESULT                         273             //结果:
#define RJ45_LBL_TEST_COMPLETED                 274             //检测完成
#define CABLE_SEQUENCE_LBL_NUMBER1              275             //近端
#define CABLE_SEQUENCE_LBL_NUMBER2              276             //远端
#define CABLE_RANGE_LBL_NUMBER                  277             //编号
#define CABLE_RANGE_LBL_LENGTH_M                278             //长度(m)
#define CABLE_RANGE_LBL_LENGTH_KM               279             //长度(km)
#define CABLE_RANGE_LBL_LENGTH_FT               280             //长度(ft)
#define CABLE_RANGE_LBL_LENGTH_KFT              281             //长度(kft)
#define CABLE_RANGE_LBL_LENGTH_YD               282             //长度(yd)
#define CABLE_RANGE_LBL_LENGTH_MI               283             //长度(mi)
#define CABLE_RANGE_LBL_UNIT                    284             //单位
#define CABLE_SEARCH_LBL_COMMON                 285             //普通寻线
#define CABLE_SEARCH_LBL_ING                    286             //寻线中…
#define USER_GUIDE_LBL_INFO                     287             //各个选项如下所示:

#endif
